tz9 itter 1
mitri4hock/java-filmorate pull request #3
Opened 2023-03-09 18:49 UTC by mitri4hock

2023-03-09 19:03 UTC, mitri4hock commented
TZ9 itter 1

2023-03-10 16:55 UTC, TarasovSam requested changes
Привет! В целом - все довольно хорошо) Особенно мне понравилось, что ты решил использовать аннотации для валидации полей, что очень полезно и облегчает разработку. Отметил то, что следует исправить и то, что можно сделать лучше.
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Здесь так же для начала следует проверить значение на null, иначе есть шанс возникновения NPE, если оно не будет передано.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Так же для начала следует проверить значение на null, иначе есть шанс возникновения NPE, если оно не будет передано.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Min(0)
Для чего ты прописал аннотацию?
Для класса User тоже самое.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int id;
Почему прописал final?
Для класса User тоже самое.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty
Две аннотации можно заменить на одну @NotBlank.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Согласно ТЗ для Film:
- название не может быть пустым (тут аннотация нужна, ты ее и написал);
- максимальная длина описания — 200 символов (тут же описание может быть пустым, т.е. его просто не написали);
- дата релиза — не раньше 28 декабря 1895 года (здесь тоже дата релиза может отсутствовать);
- продолжительность фильма должна быть положительной (и здесь тоже).
Поэтому пересмотри свои аннотации и внеси необходимые корректировки.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static int idCounter = 1;
Для чего вводишь счетчик?
Для класса User тоже самое.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(@NonNull String name, @NonNull String description, @NonNull LocalDate releaseDate, @NonNull int duration) {
Конструктор тоже можно заменить аннотацией) Для класса User тоже самое.
Прочитай про это теорию.

2023-03-10 16:55 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
Тут тоже лучше заменить на @notblank.

2023-03-11 09:22 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
при передаче NULL, "", не передачи поля - возникает связка исключений HttpMessageNotReadableException - ValueInstantiationException. Вроде NPE не возникает, т.к. на поле в классе стоит аннотация @NonNull

2023-03-11 09:35 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Min(0)
при развитии приложения- информация может начать сгружаться из БД или ещё каких бэкапов. При передаче данных или в самой БД может быть ошибка и в итоге мы можем получить отрицательные ID (что при последующей загрузке в БД может дать гирлянду ошибок при назначении поля ID - первичным ключиком - такое может произойти при переходе с одного типа БД на другой (на сколько я понимаю))

2023-03-11 09:37 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int id;
в экземпляре класса id меняться не может (иначе это другой экземпляр). Таким образом мы защищаемся от подмены инфы...

2023-03-11 09:57 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static int idCounter = 1;
сам класс хранит информацию о  нумерации поля ID своих экземпляров. В идеале, если экземпляры начнёт генерировать ещё какой-нибудь контроллер, то у нас не будут генерироваться экземпляры с перекрывающимися ID (что в последствии благоприятно отразится на передачу инфы в реляционную БД).

2023-03-11 10:17 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(@NonNull String name, @NonNull String description, @NonNull LocalDate releaseDate, @NonNull int duration) {
внутри конструкторов для классов User и Film есть логика построения (например, присвоение id идёт не из аргументов конструктора. Или поле name в конструкторе User - тоже может браться не из аргументов). Вроде как аннотация не помоет в таком случае (если я правильно понимаю) ...

2023-03-11 10:19 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NonNull
валидация имени происходит в конструкторе.
остальное поправил

2023-03-11 10:43 UTC, mitri4hock commented
провёл коммит TZ9 itter2

2023-03-12 08:53 UTC, TarasovSam reviewed
Дмитрий, спасибо за твои ответы и за внесение корректировок, плюс радует, что готов разбираться в вопросе. Оставил еще пару комментариев.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-12 08:53 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int id;
Смотри, рассуждения логичны, тут не поспоришь)
Во-первых, по сути в ТЗ ничего не было сказано по id, т.е. такое не обязательно было вводить (может быть потом).
Во-вторых, есть специальные аннотации для первичных ключей (в данном случае id - первичный ключ), которые защитят от замены до того, пока объект не будет сохранен в БД.

2023-03-12 08:53 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Min(0) // при развитии приложения - информация может начать сгружаться из БД или ещё каких бэкапов. При передаче данных или в самой БД может быть ошибка и в итоге мы можем получить отрицательные
Чаще всего в реляционных БД уже заложены ограничения, что нельзя передать id<0.
если под типами БД ты имеешь в виду реляционные и нереляционные, то переход без переработки приложения не возможен просто так))

2023-03-12 08:53 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static int idCounter = 1;
Есть специальная аннотация @GeneratedValue, которая по специально назначенной стратегии будет генерировать первичный ключ (при том, эта стратегия защитит от дублирования ключей).
По сути пока что можешь оставить кастомный вариант со счетчиком, а дальше посмотрим, в каком направлении будет развиваться приложение)

2023-03-14 02:32 UTC, merged