Add friends likes
mitri4hock/java-filmorate pull request #4
Opened 2023-03-17 02:53 UTC by mitri4hock

TZ10 itter 1

2023-03-17 19:57 UTC, TarasovSam requested changes
Дмитрий, привет!
Проверил твое задание, все довольно хорошо. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
В принципе все хорошо, но почему не проводишь логирование получения статуса?

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(!filmService.getListFilms().containsKey(film.getId())){
Принято все проверки, еще какие-то действия прописывать в реализации, а в контроллере оставлять только вызов нужного метода сервиса.
Для UserContlroller тоже самое.

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Пустую строку можно убрать, т.к. это блок объявления переменных класса.

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film createFilm(Film film) {
Может же быть случай, когда film==null, что тогда будет?
И в методе update тоже самое.

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("создан новый фильм: {}", film);
А логирование разве здесь должно быть?
И почему оно есть только для двух методов?

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
А почему решил не делать метода по удалению фильма?

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public User createUser(User user) {
Может же быть случай, когда user==null, что тогда будет?
И в методе update тоже самое.

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        log.info("создан новый пользователь: {}" , user);
А логирование разве здесь должно быть?
И почему оно есть только для двух методов?

2023-03-17 19:57 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage{
И для пользователя нет метода по удалению.

2023-03-20 07:57 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
добавил методы. Так же, перенёс хранение списка ТОП фильмов в FilmStorage интерфейс

2023-03-20 08:01 UTC, mitri4hock commented
TZ10 itter 2

2023-03-21 05:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Спасибо! Этого в ТЗ не было, но логично и удобно, чтобы метод по удалению фильма и пользователя был)
Не, в Storage у нас только CRUD методы, т.е. creat, reed (или get и getAll), update, delete. Поэтому распредели в соответствии с этим методы по классам и интерфейсам.

2023-03-21 05:27 UTC, TarasovSam reviewed
Дмитрий, спасибо за то, что вносишь корректировки по рекомендациям. Оставил еще несколько комментариев на улучшение кода.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/ErrorHandler.java
> +        log.info("объект с ID не найден. {}", e.getMessage());
Отлично, спасибо! При желании для полноты картины сообщение можно дополнить "Получен статус 404 - Not found, объект с ID не найден. {}" (для остальных тоже самое).

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ObjectWithIdNotFoundException("при обновлении фильма, фильм с id "
Перед выбрасыванием исключения добавь, пожалуйста, логирование, это позволит полностью отображать в логе все действия (удачные и не удачные).
Для пользователя тоже самое.

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
>      Boolean isContainFilm(Long id);
Про последние три метода написал в другом комментарии.

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
>      Boolean isContainUser(Long id);
Про последние два метода написал в другом комментарии.

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
На всякий продублирую и сюда.
Спасибо! Этого в ТЗ не было, но логично и удобно, чтобы метод по удалению фильма и пользователя был)
Не, в Storage у нас только CRUD методы, т.е. create, reed (или get и getAll), update, delete. Поэтому распредели в соответствии с этим методы по классам и интерфейсам.

2023-03-21 05:27 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new BadParamsException("фильм не может быть пустым");
Здесь тоже можно провести логирование перед выбрасыванием исключения, в остальных местах тоже и для пользователя тоже самое.

2023-03-24 02:50 UTC, merged