Add database
mitri4hock/java-filmorate pull request #5
Opened 2023-04-14 02:37 UTC by mitri4hock

itter 1

2023-04-14 06:44 UTC, mitri4hock commented
itter 1

2023-04-14 20:30 UTC, TarasovSam requested changes
Дмитрий, привет!
Проверил твое задание, все довольно хорошо. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

PS чтобы руками не отлавливать недостающие пробелы, отступы и прочее, используй комбинацию crtl+alt+L в каждом классе для автоформатирования.

2023-04-14 20:30 UTC, TarasovSam commented on pom.xml
> +<!--		&lt;!&ndash; https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jdbc &ndash;&gt;-->
В чем смысл комментировать зависимости? Если они не используются, их нужно удалять.
При необходимости их всегда можно вернуть через историю в гите)

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +public class GenreController {
Правильное решение выделить отдельные классы-контроллеры для жанра и рейтинга.

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Long> listLikes = new HashSet<>(); //список id лайкнувших. Поможет бороться с повторными лайками и в дальнейшем будет удобно строить систему рекомендаций (ищем подобных юзеров и
Коллекция идентификаторов пользователей, поставивших лайк - более не требуется, так как хранение мы осуществляем в БД

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Mpa mpa;
Фильмов без рейтинга быть не может в нашей системе) Следует над полем навесить @NotNull

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private Integer id;
А геттеры/сеттеры не нужны? 
Для жанра тоже.

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    //    @Builder.Default
Много закомментированного кода, его следует убрать, чтобы не засорять остальной код)

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                var s1 = getFilmById(o1).get().getRate();
Выше написать не могу, поэтому напишу здесь.
Эта реализация более не будет использовать, ее можно исключить) Также отпадает потребность в @Qualifier

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Эта реализация более не будет использовать, ее можно исключить) Также отпадает потребность в @Qualifier

2023-04-14 20:30 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Integer getCountLikes(Long filmId, Long userId) {
Для работы с лайками лучше ввести другие DAO (как с жанрами и рейтингами), так как это отдельные сущности в БД)

2023-04-14 20:30 UTC, TarasovSam commented on src/main/resources/data.sql
> +insert into  ratingMPA(ratingMPAId,ratingMPAName)
Для вставки одним запросом можно было бы использовать

merge into rating (rating_id, name)
values (1, 'G'),
       (2, 'PG'),
       (3, 'PG-13'),
       (4, 'R'),
       (5, 'NC-17');

Аналогично с жанрами)

2023-04-14 20:30 UTC, TarasovSam commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Можно было бы ввести ограничение на уникальность логина и почты на уровне таблицы в БД)

create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);

2023-04-17 08:54 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private Integer id;
вроде они там есть из-за аннотации (даже используется в Genre)

2023-04-17 09:06 UTC, mitri4hock commented
itter 2

2023-04-17 19:25 UTC, TarasovSam reviewed
Дмитрий, привет!
Проверил твое задание, спасибо за работу и за то, что дорабатываешь код.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-04-18 02:13 UTC, merged